#!/usr/bin/env bun
/**
 * Reads house actor .ts files from house/actors/ and produces a generated
 * module that exports them as an inline Map for the compiled binary.
 *
 * Output: src/generated/house-actors.ts
 */
import { readdirSync, readFileSync, writeFileSync, mkdirSync } from "fs"
import { resolve, dirname, basename } from "path"

const root = resolve(dirname(new URL(import.meta.url).pathname), "..")
const actorsDir = resolve(root, "house/actors")
const outDir = resolve(root, "src/generated")
const outPath = resolve(outDir, "house-actors.ts")

const files = readdirSync(actorsDir).filter((f) => f.endsWith(".ts")).sort()

if (files.length === 0) {
  console.error("[inline-house-actors] ERROR: No .ts files found in house/actors/")
  process.exit(1)
}

const actorBlocks: string[] = []

for (const file of files) {
  const src = readFileSync(resolve(actorsDir, file), "utf-8")

  // Strip the export default and trailing newlines — we'll re-wrap it
  const cleaned = src
    .replace(/^export default actor[\s;]*$/m, "")
    .replace(/\n+$/, "")

  const id = basename(file, ".ts")
  actorBlocks.push(`  // --- ${file} ---\n  (() => {\n${indent(cleaned, 4)}\n    return actor\n  })()`)
}

function indent(text: string, spaces: number): string {
  const pad = " ".repeat(spaces)
  return text
    .split("\n")
    .map((line) => (line.trim() ? pad + line : line))
    .join("\n")
}

const output = `// AUTO-GENERATED by scripts/inline-house-actors.ts — do not edit
type EmbeddedActor = {
  id: string
  displayName?: string
  description?: string
  profileName?: string
  decide: (context: any) => { action: string; amount?: number }
}

const actors: EmbeddedActor[] = [
${actorBlocks.join(",\n")},
]

export function getEmbeddedHouseActorsMap(): Map<string, EmbeddedActor> {
  const map = new Map<string, EmbeddedActor>()
  for (const actor of actors) {
    map.set(actor.id, actor)
  }
  return map
}
`

mkdirSync(outDir, { recursive: true })
writeFileSync(outPath, output)
console.log(`[inline-house-actors] Wrote ${outPath} (${files.length} actors: ${files.map((f) => basename(f, ".ts")).join(", ")})`)
