// Auto-generated by pokurr – do not edit manually.
// Regenerate with: pokurr types
// ──────────────────────────────────────────────────────────────────

// ── Core Decision Types ──────────────────────────────────────────

export type PokerAction = "fold" | "check" | "call" | "bet" | "raise" | "all-in"

export type PokerPosition = "UTG" | "MP" | "CO" | "BTN" | "SB" | "BB"

export type DecisionContext = {
  heroCards: string[]
  board: string[]
  street: "preflop" | "flop" | "turn" | "river"
  position: PokerPosition
  inPosition: boolean
  toCall: number
  potSize: number
  stack: number
  legalActions: PokerAction[]
  playersInHand: number
}

export type StrategyDecision = {
  action: PokerAction
  amount?: number
  reason?: string
}

// ── Card Types ───────────────────────────────────────────────────

type Rank = "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" | "T" | "J" | "Q" | "K" | "A"
type Suit = "h" | "d" | "c" | "s"
type Card = `${Rank}${Suit}`

interface CardObject {
  rank: number
  suit: number
}

// ── Hand Evaluation ──────────────────────────────────────────────

interface HandRank {
  category: number
  categoryName: string
  rank: number
  cards: CardObject[]
}

// ── Range ────────────────────────────────────────────────────────

interface Range {
  includes(combo: string): boolean
  combos(): string[]
  readonly size: number
  readonly percentile: number
  readonly strength: number
  toString(): string
}

interface RangeConstructor {
  new (notation: string): Range
  ultraStrong(deadCards?: string[]): Range
  strong(deadCards?: string[]): Range
  medium(deadCards?: string[]): Range
  loose(deadCards?: string[]): Range
  sklansky(groupNumber: number, deadCards?: string[]): Range
  strongestHands(percent: number, numberOfOpponents?: number): string[]
}

// ── HandEquity ───────────────────────────────────────────────────

interface HandEquity {
  against(villain: string | Range, board?: string[], iterations?: number): Promise<{ equity: number; wins: number; ties: number; total: number }>
}

interface HandEquityConstructor {
  new (hand: string): HandEquity
}

// ── RangeEquity ──────────────────────────────────────────────────

interface RangeEquity {
  against(villain: Range, board?: string[], iterations?: number): Promise<{ equity: number; wins: number; ties: number; total: number }>
}

interface RangeEquityConstructor {
  new (range: Range): RangeEquity
}

// ── Deck ─────────────────────────────────────────────────────────

interface Deck {
  shuffle(): Deck
  draw(count?: number): Card[]
  remaining(): number
  remove(cards: string[]): Deck
}

interface DeckConstructor {
  new (): Deck
}

// ── Board Texture ────────────────────────────────────────────

interface BoardTexture {
  monotone: boolean
  twoTone: boolean
  rainbow: boolean
  flushPossible: boolean
  flushDrawPossible: boolean
  dominantSuit: Suit | null
  suitCounts: Record<string, number>
  straightPossible: boolean
  highlyConnected: boolean
  paired: boolean
  trips: boolean
  pairRank: number | null
  highCard: number
  hasAce: boolean
  hasBroadway: boolean
  wetness: number
  cardCount: number
}

interface DrawAnalysis {
  flushDraw: boolean
  flushDrawSuit: Suit | null
  flushDrawOuts: number
  madeFlush: boolean
  openEndedStraightDraw: boolean
  gutshot: boolean
  doubleGutshot: boolean
  straightDrawOuts: number
  madeStraight: boolean
  comboDrawCount: number
  totalOuts: number
  overcardCount: number
}

// ── Equity Engine ────────────────────────────────────────────────

interface EquityResult {
  bestHandCount: number
  possibleHandsCount: number
  tieHandCount: number
}

interface EquityEngine {
  equityWithBackend(
    backend: "wasm",
    hands: string[][],
    board?: string[],
    iterations?: number,
  ): Promise<EquityResult[]>
}

// ── Strategy Feature ─────────────────────────────────────────────

interface StrategyFeature {
  rangeForProfile(profileName: string, position: PokerPosition): Range | null
  sampleRangeHand(profileName: string, deadCards?: string[], rng?: any, position?: PokerPosition): string[] | null
  estimateEquity(context: {
    heroCards: [string, string]
    board?: string[]
    villainRange?: string
    iterations?: number
  }): Promise<number>
  listProfiles(): string[]
}

// ── Global Declarations ──────────────────────────────────────────

declare global {
  /** Hand vs hand equity calculation */
  const equity: (hands: string[][], board?: string[], iterations?: number) => Promise<EquityResult[]>
  /** Full equity engine with backend selection */
  const equityEngine: EquityEngine
  /** Evaluate the best 5-card hand from 5-7 cards */
  const evaluateHand: (cards: string[]) => HandRank
  /** Compare two HandRank results (-1, 0, 1) */
  const compareHands: (a: HandRank, b: HandRank) => number
  /** Combo equity analysis: new HandEquity("AhKd") */
  const HandEquity: HandEquityConstructor
  /** Hand range: new Range("QQ+,AKs") */
  const Range: RangeConstructor
  /** Range vs range equity */
  const RangeEquity: RangeEquityConstructor
  /** Quick range vs range comparison */
  const compareRanges: (ours: Range, theirs: Range, opts?: { board?: string[]; iterations?: number }) => Promise<{ hero: number; villain: number; tie: number }>
  /** Deck: new Deck(), .shuffle(), .draw() */
  const Deck: DeckConstructor
  /** Parse card string to CardObject */
  const stringToCard: (s: string) => CardObject
  /** CardObject to string */
  const cardToString: (c: CardObject) => string
  /** Normalize hole cards to combo notation: "AcKd" → "AKo" */
  const normalizeCombo: (cards: string[]) => string
  /** Analyze board texture: suit distribution, connectedness, wetness */
  const analyzeBoard: (board: string[]) => BoardTexture
  /** Analyze hero's draws against the board: flush draws, straight draws, outs */
  const analyzeDraws: (heroCards: string[], board: string[]) => DrawAnalysis
  /** Built-in strategy engine with profiles and equity estimation */
  const strategy: StrategyFeature
  /** Full luca container — use container.feature() to access any capability */
  const container: AGIContainer
}

// ── Container (lightweight surface for strategy authors) ─────────

interface AGIContainer {
  /** Access a container feature by name */
  feature(name: string, options?: { enable?: boolean }): any
  /** Container path utilities */
  paths: {
    resolve(...segments: string[]): string
    root: string
  }
  /** Container state store */
  state: {
    get(key: string): any
    set(key: string, value: any): void
  }
  /** Utility helpers (uuid, hashing, etc.) */
  utils: Record<string, (...args: any[]) => any>
  /** Content database (docs) */
  docs: any
}

export {}
